CREATE TABLE IF NOT EXISTS `cotizaciones` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(60) NOT NULL UNIQUE,
  `cliente` VARCHAR(160) NOT NULL,
  `email` VARCHAR(254) NOT NULL,
  `telefono` VARCHAR(30) NOT NULL,
  `documento` VARCHAR(30) NOT NULL,
  `direccion` VARCHAR(300) NOT NULL,
  `emisor` VARCHAR(160) NOT NULL,
  `datos_emisor` VARCHAR(500) NOT NULL,
  `moneda` VARCHAR(3) NOT NULL,
  `validez` DATE NOT NULL,
  `condiciones` TEXT NOT NULL,
  `conceptos` JSON NOT NULL,
  `subtotal` DECIMAL(14,2) NOT NULL,
  `descuento` DECIMAL(14,2) NOT NULL,
  `tasa` DECIMAL(5,2) NOT NULL,
  `impuesto` DECIMAL(14,2) NOT NULL,
  `total` DECIMAL(14,2) NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'borrador',
  `contacto_id` INTEGER NULL,
  `revision` INTEGER NOT NULL DEFAULT 1,
  `historial` JSON NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;
