import { useEffect, useState, type SubmitEvent } from 'react';
import { useAdminAuth } from '../context';
import { panelRequest, errorMessage } from '../services/panelApi';
import { useRequestStatus } from '../hooks/useRequestStatus';
type Attention={estado:string;responsable:string;notas:string;respuesta:string;revision:number;historial:{accion:string;usuario:number;fecha:string}[]};
export default function AttentionEditor({resource,id,onSaved}:{resource:'messages'|'reclamaciones';id:number;onSaved?:()=>void}){
 const {token}=useAdminAuth();const [reload,setReload]=useState(0),[form,setForm]=useState<Attention|null>(null);
 const [busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[notice,setNotice]=useState('');
 const {loading,error,setLoading,setError}=useRequestStatus(resource+id+':'+reload);const path='seguimiento/'+resource+'/'+id;
 useEffect(()=>{const c=new AbortController();let live=true;void panelRequest<{item:Attention}>(path,token,'GET',undefined,c.signal).then(r=>{if(live)setForm(r.item)}).catch(e=>{if(live)setError(errorMessage(e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false;c.abort()};},[path,token,reload,setLoading,setError]);
 const save=async(e:SubmitEvent<HTMLFormElement>)=>{e.preventDefault();if(!form||busy)return;setBusy(true);setActionError('');setNotice('');try{const payload={estado:form.estado,responsable:form.responsable,notas:form.notas,respuesta:form.respuesta,revision:form.revision};const r=await panelRequest<{item:Attention}>(path,token,'PUT',payload);setForm(r.item);setNotice('Seguimiento guardado.');onSaved?.();}catch(e){setActionError(errorMessage(e))}finally{setBusy(false)}};
 const receipt=async()=>{if(busy)return;setBusy(true);setActionError('');try{const r=await panelRequest<{mensaje:string}>(path+'/constancia',token,'POST');setNotice(r.mensaje)}catch(e){setActionError(errorMessage(e))}finally{setBusy(false)}};
 const send=async()=>{if(!form||busy)return;setBusy(true);setActionError('');setNotice('');try{const r=await panelRequest<{mensaje:string}>(path+'/correo',token,'POST',{revision:form.revision});setNotice(r.mensaje)}catch(e){setActionError(errorMessage(e))}finally{setBusy(false)}};
 return <section className="hp-card"><h3>Seguimiento de atención</h3><button className="hp-btn" disabled={busy||loading} onClick={()=>setReload(v=>v+1)}>Recargar seguimiento</button>{loading?<p role="status">Cargando seguimiento…</p>:error?<p role="alert" className="hp-error">{error}</p>:form&&<form onSubmit={save} className="hp-form"><fieldset disabled={busy}><label>Estado<select value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}>{['nuevo','en_proceso','atendido','archivado'].map(v=><option key={v} value={v}>{v.replace('_',' ')}</option>)}</select></label><label>Responsable<input value={form.responsable} maxLength={100} onChange={e=>setForm({...form,responsable:e.target.value})}/></label><label>Notas internas<textarea value={form.notas} maxLength={10000} onChange={e=>setForm({...form,notas:e.target.value})}/></label><label>Respuesta al cliente<textarea value={form.respuesta} maxLength={10000} onChange={e=>setForm({...form,respuesta:e.target.value})}/></label></fieldset>{actionError&&<p role="alert" className="hp-error">{actionError}</p>}{notice&&<p role="status" className="hp-notice">{notice}</p>}<div className="hp-actions"><button type="button" className="hp-btn" disabled={busy} onClick={()=>void receipt()}>Reenviar constancia / notificación</button><button className="hp-btn hp-btn-primary" disabled={busy}>Guardar seguimiento</button><button type="button" className="hp-btn" disabled={busy||!form.respuesta} onClick={()=>void send()}>Enviar respuesta guardada</button></div><p>El correo envía la última respuesta guardada. Conserva tus cambios antes de enviarla.</p><h4>Historial</h4>{form.historial.length?<ul>{form.historial.map((h,i)=><li key={i}>{new Date(h.fecha).toLocaleString('es-PE')} · {h.accion} · Administrador #{h.usuario}</li>)}</ul>:<p>Aún no hay cambios de seguimiento.</p>}</form>}</section>;
}
