import { useEffect, useRef, useState, type SubmitEvent } from 'react';
import { useAdminAuth } from '../context';
import { panelRequest, errorMessage } from '../services/panelApi';
import { useRequestStatus } from '../hooks/useRequestStatus';
import { useUnsavedChanges } from '../unsaved/unsavedContext';
import { useLatest } from '../hooks/useLatest';
type Attention={estado:string;responsable:string;notas:string;respuesta:string;revision:number;historial:{accion:string;usuario:number;fecha:string}[]};
// Fusiona el seguimiento fresco del servidor con el borrador: los campos que la persona ya cambió se conservan; el resto toma el valor del servidor.
// La revisión siempre es la del servidor, así que guardar después no choca (409) con un cambio de estado hecho por una acción rápida.
const mergeDraft=(current:Attention,base:Attention,fresh:Attention):Attention=>{const keep=(k:'estado'|'responsable'|'notas'|'respuesta')=>current[k]!==base[k];return{...fresh,estado:keep('estado')?current.estado:fresh.estado,responsable:keep('responsable')?current.responsable:fresh.responsable,notas:keep('notas')?current.notas:fresh.notas,respuesta:keep('respuesta')?current.respuesta:fresh.respuesta}};
export default function AttentionEditor({resource,id,onSaved,syncKey=0}:{resource:'messages'|'reclamaciones';id:number;onSaved?:()=>void;syncKey?:number}){
 const {token}=useAdminAuth();const latestToken=useLatest(token);const [reload,setReload]=useState(0),[form,setForm]=useState<Attention|null>(null),[saved,setSaved]=useState<Attention|null>(null);
 // Hay cambios cuando el formulario difiere de la última copia guardada (la cargada o la devuelta por el último guardado correcto).
 const dirty=!!form&&!!saved&&(form.estado!==saved.estado||form.responsable!==saved.responsable||form.notas!==saved.notas||form.respuesta!==saved.respuesta);
 const savedRef=useLatest(saved),synced=useRef(syncKey);
 // Un cambio de `syncKey` (p. ej. el estado se actualizó desde una acción rápida) actualiza revisión y estado SIN reconstruir el editor ni borrar lo escrito.
 useEffect(()=>{if(synced.current===syncKey)return;synced.current=syncKey;const c=new AbortController();let live=true;
 void panelRequest<{item:Attention}>('seguimiento/'+resource+'/'+id,latestToken.current,'GET',undefined,c.signal).then(r=>{if(!live)return;const base=savedRef.current;setSaved(r.item);setForm(current=>current&&base?mergeDraft(current,base,r.item):r.item)}).catch(()=>{/* sin red el borrador queda intacto; guardar mostrará un conflicto si lo hay */});
 return()=>{live=false;c.abort()};},[syncKey,resource,id,latestToken,savedRef]);
 const confirmLeave=useUnsavedChanges(dirty,(resource==='messages'?'seguimiento de la consulta #':'seguimiento de la reclamación #')+id);
 const [busy,setBusy]=useState(false),[actionError,setActionError]=useState(''),[notice,setNotice]=useState('');
 const {loading,error,setLoading,setError}=useRequestStatus(resource+id+':'+reload);const path='seguimiento/'+resource+'/'+id;
 useEffect(()=>{const c=new AbortController();let live=true;void panelRequest<{item:Attention}>(path,latestToken.current,'GET',undefined,c.signal).then(r=>{if(live){setForm(r.item);setSaved(r.item)}}).catch(e=>{if(live)setError(errorMessage(e))}).finally(()=>{if(live)setLoading(false)});return()=>{live=false;c.abort()};},[path,latestToken,reload,setLoading,setError]);
 const save=async(e:SubmitEvent<HTMLFormElement>)=>{e.preventDefault();if(!form||busy)return;setBusy(true);setActionError('');setNotice('');try{const payload={estado:form.estado,responsable:form.responsable,notas:form.notas,respuesta:form.respuesta,revision:form.revision};const r=await panelRequest<{item:Attention}>(path,token,'PUT',payload);setForm(r.item);setSaved(r.item);setNotice('Seguimiento guardado.');onSaved?.();}catch(e){setActionError(errorMessage(e))}finally{setBusy(false)}};
 const receipt=async()=>{if(busy)return;setBusy(true);setActionError('');try{const r=await panelRequest<{mensaje:string}>(path+'/constancia',token,'POST');setNotice(r.mensaje)}catch(e){setActionError(errorMessage(e))}finally{setBusy(false)}};
 const send=async()=>{if(!form||busy)return;setBusy(true);setActionError('');setNotice('');try{const r=await panelRequest<{mensaje:string}>(path+'/correo',token,'POST',{revision:form.revision});setNotice(r.mensaje)}catch(e){setActionError(errorMessage(e))}finally{setBusy(false)}};
 return <section className="hp-card"><h3>Seguimiento de atención</h3><button className="hp-btn" disabled={busy||loading} onClick={()=>confirmLeave(()=>setReload(v=>v+1))}>Recargar seguimiento</button>{loading?<p role="status">Cargando seguimiento…</p>:error?<p role="alert" className="hp-error">{error}</p>:form&&<form onSubmit={save} className="hp-form"><fieldset disabled={busy}><label>Estado<select value={form.estado} onChange={e=>setForm({...form,estado:e.target.value})}>{['nuevo','en_proceso','atendido','archivado'].map(v=><option key={v} value={v}>{v.replace('_',' ')}</option>)}</select></label><label>Responsable<input value={form.responsable} maxLength={100} onChange={e=>setForm({...form,responsable:e.target.value})}/></label><label>Notas internas<textarea value={form.notas} maxLength={10000} onChange={e=>setForm({...form,notas:e.target.value})}/></label><label>Respuesta al cliente<textarea value={form.respuesta} maxLength={10000} onChange={e=>setForm({...form,respuesta:e.target.value})}/></label></fieldset>{actionError&&<p role="alert" className="hp-error">{actionError}</p>}{notice&&<p role="status" className="hp-notice">{notice}</p>}<div className="hp-actions"><button type="button" className="hp-btn" disabled={busy} onClick={()=>void receipt()}>Reenviar constancia / notificación</button><button className="hp-btn hp-btn-primary" disabled={busy}>Guardar seguimiento</button><button type="button" className="hp-btn" disabled={busy||!form.respuesta} onClick={()=>void send()}>Enviar respuesta guardada</button></div>{dirty&&<p className="hp-form-hint">Tienes cambios sin guardar. El correo enviaría la última respuesta guardada, no lo que ves ahora.</p>}<p>El correo envía la última respuesta guardada. Conserva tus cambios antes de enviarla.</p><h4>Historial</h4>{form.historial.length?<ul>{form.historial.map((h,i)=><li key={i}>{new Date(h.fecha).toLocaleString('es-PE')} · {h.accion} · Administrador #{h.usuario}</li>)}</ul>:<p>Aún no hay cambios de seguimiento.</p>}</form>}</section>;
}
