import { useRef, useState, type SubmitEvent } from 'react';
import { useAdminAuth } from '../context';
import { panelRequest, errorMessage } from '../services/panelApi';
import PanelDialog from './PanelDialog';
import type { Quote, QuoteInput } from '../types/quotes';
export default function QuoteForm({initial,onClose,onSaved}:{initial?:Quote|QuoteInput;onClose:()=>void;onSaved:()=>void}) {
 const {token}=useAdminAuth();const lock=useRef(false);
 const [form,setForm]=useState<QuoteInput>(()=>({cliente:initial?.cliente||'',email:initial?.email||'',telefono:initial?.telefono||'',documento:initial?.documento||'',direccion:initial?.direccion||'',emisor:initial?.emisor||'',datos_emisor:initial?.datos_emisor||'',moneda:initial?.moneda||'PEN',validez:initial?.validez||new Date(Date.now()+7*86400000).toISOString().slice(0,10),condiciones:initial?.condiciones||'',conceptos:initial?.conceptos.map(({descripcion,cantidad,precio})=>({descripcion,cantidad,precio:Number(precio)}))||[{descripcion:'',cantidad:1,precio:0}],descuento:Number(initial?.descuento||0),tasa:Number(initial?.tasa??18),...(initial?.contacto_id?{contacto_id:initial.contacto_id}:{})}));
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const editing=initial && 'id' in initial;
 const setText=(key:keyof QuoteInput,value:string)=>setForm(v=>({...v,[key]:value}));
 const submit=async(event:SubmitEvent<HTMLFormElement>)=>{event.preventDefault();if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await panelRequest(editing?'cotizaciones/'+initial.id:'cotizaciones',token,editing?'PUT':'POST',{...form,...(editing?{revision:initial.revision}:{})});onSaved();}catch(e){setError(errorMessage(e));}finally{lock.current=false;setBusy(false);}};
 const textFields:[keyof QuoteInput,string,number][]=[['cliente','Cliente',160],['email','Correo del cliente',254],['telefono','Teléfono',30],['documento','Documento',30],['direccion','Dirección',300],['emisor','Emisor de la propuesta',160],['datos_emisor','Datos del emisor',500]];
 return <PanelDialog title={editing?'Editar borrador':'Nueva cotización'} busy={busy} onClose={onClose}><form onSubmit={submit} className="hp-form">
 {error&&<p role="alert" className="hp-error">{error}</p>}<fieldset disabled={busy}><div className="hp-form-grid">{textFields.map(([key,title,max])=><label key={key}>{title}<input type={key==='email'?'email':'text'} value={String(form[key])} maxLength={max} minLength={key==='cliente'||key==='emisor'?2:undefined} required={key==='cliente'||key==='emisor'} onChange={e=>setText(key,e.target.value)}/></label>)}
 <label>Moneda<select value={form.moneda} onChange={e=>setText('moneda',e.target.value)}><option value="PEN">Soles (PEN)</option><option value="USD">Dólares (USD)</option></select></label><label>Válida hasta<input type="date" required value={form.validez} onChange={e=>setText('validez',e.target.value)}/></label></div>
 <h3>Conceptos</h3>{form.conceptos.map((line,i)=><div className="hp-form-grid" key={i}><label>Descripción {i+1}<input required minLength={2} maxLength={500} value={line.descripcion} onChange={e=>setForm(v=>({...v,conceptos:v.conceptos.map((x,n)=>n===i?{...x,descripcion:e.target.value}:x)}))}/></label><label>Cantidad<input type="number" min={1} max={10000} step={1} required value={line.cantidad} onChange={e=>setForm(v=>({...v,conceptos:v.conceptos.map((x,n)=>n===i?{...x,cantidad:Number(e.target.value)}:x)}))}/></label><label>Precio unitario<input type="number" min={0} max={1000000} step=".01" required value={line.precio} onChange={e=>setForm(v=>({...v,conceptos:v.conceptos.map((x,n)=>n===i?{...x,precio:Number(e.target.value)}:x)}))}/></label><button className="hp-btn" type="button" disabled={form.conceptos.length===1} onClick={()=>setForm(v=>({...v,conceptos:v.conceptos.filter((_,n)=>n!==i)}))}>Quitar concepto {i+1}</button></div>)}
 <button className="hp-btn" type="button" disabled={form.conceptos.length>=50} onClick={()=>setForm(v=>({...v,conceptos:[...v.conceptos,{descripcion:'',cantidad:1,precio:0}]}))}>Añadir concepto</button>
 <div className="hp-form-grid"><label>Descuento<input type="number" min={0} max={10000000000} step=".01" required value={form.descuento} onChange={e=>setForm(v=>({...v,descuento:Number(e.target.value)}))}/></label><label>Impuesto (%)<input type="number" min={0} max={100} step=".01" required value={form.tasa} onChange={e=>setForm(v=>({...v,tasa:Number(e.target.value)}))}/></label></div><label>Condiciones<textarea value={form.condiciones} maxLength={5000} onChange={e=>setText('condiciones',e.target.value)}/></label>
 <p>El total se calcula al guardar. Revisa los datos del emisor antes de enviar la propuesta.</p></fieldset><div className="hp-actions"><button className="hp-btn" type="button" onClick={onClose} disabled={busy}>Cancelar</button><button className="hp-btn hp-btn-primary" disabled={busy}>{busy?'Guardando…':'Guardar borrador'}</button></div></form></PanelDialog>;
}
