import { useEffect, useRef, useState, type SubmitEvent } from 'react';
import { useAdminAuth } from '../context';
import { PanelApiError, panelRequest, errorMessage } from '../services/panelApi';
import PanelDialog from './PanelDialog';
import { useUnsavedChangesControl } from '../unsaved/unsavedContext';
import type { Quote, QuoteInput } from '../types/quotes';
const CREATE_TIMEOUT_MS=25000,CHECK_TIMEOUT_MS=15000;
export default function QuoteForm({initial,onClose,onSaved,related=[]}:{initial?:Quote|QuoteInput;onClose:()=>void;onSaved:()=>void;related?:{numero:string;estado:string}[]}) {
 const {token}=useAdminAuth();const lock=useRef(false);
 const [form,setForm]=useState<QuoteInput>(()=>({cliente:initial?.cliente||'',email:initial?.email||'',telefono:initial?.telefono||'',documento:initial?.documento||'',direccion:initial?.direccion||'',emisor:initial?.emisor||'',datos_emisor:initial?.datos_emisor||'',moneda:initial?.moneda||'PEN',validez:initial?.validez||new Date(Date.now()+7*86400000).toISOString().slice(0,10),condiciones:initial?.condiciones||'',conceptos:initial?.conceptos.map(({descripcion,cantidad,precio})=>({descripcion,cantidad,precio:Number(precio)}))||[{descripcion:'',cantidad:1,precio:0}],descuento:Number(initial?.descuento||0),tasa:Number(initial?.tasa??18),...(initial?.contacto_id?{contacto_id:initial.contacto_id}:{})}));
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 // Cambios = el formulario difiere de lo que se abrió (o de lo último guardado). Cerrar con cambios pide confirmación.
 const [baseline,setBaseline]=useState(()=>JSON.stringify(form));
 const {confirmLeave,clear}=useUnsavedChangesControl(JSON.stringify(form)!==baseline,'cotización');
 const requestClose=()=>confirmLeave(onClose);
 const editing=initial && 'id' in initial;
 const setText=(key:keyof QuoteInput,value:string)=>setForm(v=>({...v,[key]:value}));
 // El backend no ofrece idempotencia: una creación sin resultado conocido (red, timeout, 5xx o 2xx ilegible) puede haberse guardado. El formulario NO repite el POST por sí solo;
 // permite comprobar la lista y exige una confirmación explícita que advierte del posible duplicado. Editar usa `revision`, así que un reintento obsoleto responde 409.
 const [phase,setPhase]=useState<'idle'|'uncertain'|'confirming'>('idle'),[check,setCheck]=useState<{state:'idle'|'loading'|'done'|'error';matches:{numero:string;estado:string}[]}>({state:'idle',matches:[]});
 const attemptAt=useRef(0),uncertainBox=useRef<HTMLDivElement>(null),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false};},[]);
 useEffect(()=>{if(phase==='uncertain'&&check.state==='idle')uncertainBox.current?.focus();},[phase,check.state]);
 const post=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setPhase(current=>current==='confirming'?'uncertain':current);const ctrl=new AbortController(),timer=window.setTimeout(()=>ctrl.abort(),CREATE_TIMEOUT_MS);attemptAt.current=Date.now();
  try{await panelRequest(editing?'cotizaciones/'+initial.id:'cotizaciones',token,editing?'PUT':'POST',{...form,...(editing?{revision:initial.revision}:{})},ctrl.signal);setBaseline(JSON.stringify(form));clear();onSaved();}
  catch(e){const uncertain=!editing&&(!(e instanceof PanelApiError)||e.status>=500||e.status<400);if(!alive.current)return;if(uncertain){setPhase('uncertain');setCheck({state:'idle',matches:[]});}else{setPhase('idle');setError(errorMessage(e));}}
  finally{window.clearTimeout(timer);lock.current=false;if(alive.current)setBusy(false);}};
 const checkList=async()=>{setCheck({state:'loading',matches:[]});const ctrl=new AbortController(),timer=window.setTimeout(()=>ctrl.abort(),CHECK_TIMEOUT_MS);
  try{const data=await panelRequest<{items:Quote[]}>('cotizaciones?'+new URLSearchParams({page:'1',limit:'20',search:form.cliente.trim().slice(0,100)}),token,'GET',undefined,ctrl.signal);
   const since=attemptAt.current-120000; // margen por diferencias de reloj entre el navegador y el servidor
   if(alive.current)setCheck({state:'done',matches:data.items.filter(q=>q.cliente===form.cliente.trim()&&!!q.createdAt&&new Date(q.createdAt).getTime()>=since&&(!form.contacto_id||q.contacto_id===form.contacto_id)).map(q=>({numero:q.numero,estado:q.estado}))});}
  catch{if(alive.current)setCheck({state:'error',matches:[]});}finally{window.clearTimeout(timer);}};
 const submit=(event:SubmitEvent<HTMLFormElement>)=>{event.preventDefault();if(lock.current)return;if(phase!=='idle'){setPhase('confirming');return;}void post();};
 const textFields:[keyof QuoteInput,string,number][]=[['cliente','Cliente',160],['email','Correo del cliente',254],['telefono','Teléfono',30],['documento','Documento',30],['direccion','Dirección',300],['emisor','Emisor de la propuesta',160],['datos_emisor','Datos del emisor',500]];
 return <PanelDialog title={editing?'Editar borrador':'Nueva cotización'} busy={busy} onClose={requestClose}><form onSubmit={submit} className="hp-form">
 {error&&<p role="alert" className="hp-error">{error}</p>}{related.length>0&&phase==='idle'&&<p role="status" className="hp-notice" data-quote-related>Esta consulta ya tiene {related.length===1?'una cotización asociada':related.length+' cotizaciones asociadas'}: {related.map(q=>q.numero+' ('+q.estado+')').join(', ')}. Continúa solo si necesitas otra.</p>}{phase!=='idle'&&<div ref={uncertainBox} tabIndex={-1} role="alert" className="hp-error" data-quote-uncertain={phase}><p>No pudimos confirmar si la cotización se guardó: puede que el servidor la haya creado y solo se haya perdido la respuesta. Tu borrador se conserva y no se volverá a enviar automáticamente.</p>{check.state==='loading'&&<p role="status">Comprobando la lista…</p>}{check.state==='error'&&<p>No pudimos consultar la lista. Puedes reintentarlo.</p>}{check.state==='done'&&(check.matches.length?<><p>Encontramos {check.matches.length===1?'una cotización reciente':check.matches.length+' cotizaciones recientes'} de este cliente{form.contacto_id?' asociada(s) a la misma consulta':''}. Es posible que ya se haya guardado, pero no podemos asegurar que sea esta solicitud:</p><ul data-quote-matches>{check.matches.map(q=><li key={q.numero}>{q.numero} · {q.estado}</li>)}</ul><div className="hp-actions"><button type="button" className="hp-btn hp-btn-primary" onClick={()=>{clear();onSaved();}}>Ya se guardó: cerrar y actualizar la lista</button></div></>:<p>No encontramos una cotización reciente de este cliente. Eso no garantiza que no se haya creado: puede tardar en aparecer.</p>)}{phase==='confirming'?<><p><strong>Si la solicitud anterior sí llegó, guardar otra vez creará una cotización duplicada.</strong></p><div className="hp-actions"><button type="button" className="hp-btn hp-btn-primary" disabled={busy} onClick={()=>setPhase('uncertain')}>Volver</button><button type="button" className="hp-btn hp-btn-danger" disabled={busy} onClick={()=>void post()}>Guardar de todos modos</button></div></>:<div className="hp-actions"><button type="button" className="hp-btn" disabled={busy||check.state==='loading'} onClick={()=>void checkList()}>{check.state==='idle'?'Comprobar en la lista':'Comprobar de nuevo'}</button></div>}</div>}<fieldset disabled={busy}><div className="hp-form-grid">{textFields.map(([key,title,max])=><label key={key}>{title}<input type={key==='email'?'email':'text'} value={String(form[key])} maxLength={max} minLength={key==='cliente'||key==='emisor'?2:undefined} required={key==='cliente'||key==='emisor'} onChange={e=>setText(key,e.target.value)}/></label>)}
 <label>Moneda<select value={form.moneda} onChange={e=>setText('moneda',e.target.value)}><option value="PEN">Soles (PEN)</option><option value="USD">Dólares (USD)</option></select></label><label>Válida hasta<input type="date" required value={form.validez} onChange={e=>setText('validez',e.target.value)}/></label></div>
 <h3>Conceptos</h3>{form.conceptos.map((line,i)=><div className="hp-form-grid" key={i}><label>Descripción {i+1}<input required minLength={2} maxLength={500} value={line.descripcion} onChange={e=>setForm(v=>({...v,conceptos:v.conceptos.map((x,n)=>n===i?{...x,descripcion:e.target.value}:x)}))}/></label><label>Cantidad<input type="number" min={1} max={10000} step={1} required value={line.cantidad} onChange={e=>setForm(v=>({...v,conceptos:v.conceptos.map((x,n)=>n===i?{...x,cantidad:Number(e.target.value)}:x)}))}/></label><label>Precio unitario<input type="number" min={0} max={1000000} step=".01" required value={line.precio} onChange={e=>setForm(v=>({...v,conceptos:v.conceptos.map((x,n)=>n===i?{...x,precio:Number(e.target.value)}:x)}))}/></label><button className="hp-btn" type="button" disabled={form.conceptos.length===1} onClick={()=>setForm(v=>({...v,conceptos:v.conceptos.filter((_,n)=>n!==i)}))}>Quitar concepto {i+1}</button></div>)}
 <button className="hp-btn" type="button" disabled={form.conceptos.length>=50} onClick={()=>setForm(v=>({...v,conceptos:[...v.conceptos,{descripcion:'',cantidad:1,precio:0}]}))}>Añadir concepto</button>
 <div className="hp-form-grid"><label>Descuento<input type="number" min={0} max={10000000000} step=".01" required value={form.descuento} onChange={e=>setForm(v=>({...v,descuento:Number(e.target.value)}))}/></label><label>Impuesto (%)<input type="number" min={0} max={100} step=".01" required value={form.tasa} onChange={e=>setForm(v=>({...v,tasa:Number(e.target.value)}))}/></label></div><label>Condiciones<textarea value={form.condiciones} maxLength={5000} onChange={e=>setText('condiciones',e.target.value)}/></label>
 <p>El total se calcula al guardar. Revisa los datos del emisor antes de enviar la propuesta.</p></fieldset><div className="hp-actions"><button className="hp-btn" type="button" onClick={requestClose} disabled={busy}>Cancelar</button><button className="hp-btn hp-btn-primary" disabled={busy||phase==='confirming'}>{busy?'Guardando…':phase==='idle'?'Guardar borrador':'Guardar de nuevo…'}</button></div></form></PanelDialog>;
}
